### ISSUE TITLE
active_support.rb:79:in `block in load_missing_constant': uninitialized constant URI::Generic (NameError)

### ISSUE THREAD

**Issue by mcat56** [bih/spotify-ruby#68]
After simply adding the gem to my gem file and bundle installing, then going into rails c I get the following error: 

Users/**/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/active_support.rb:79:in `block in load_missing_constant': uninitialized constant URI::Generic (NameError)

**Comment by bih** [comment]
Hello!

Thanks for submitting an issue. Looking at the stack trace, this doesn't seem to be related to the `spotify-ruby` gem? We don't seem to be using the `URI` module. Could you confirm?

**Comment by mcat56** [comment]
The issue resolved, I believe it was not related to the gem

Thank you

Mary
